name: 编译工程
on: [push]
jobs:
  build-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: 编译程序
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: 执行程序
        run: ls build && ./build/Hello